# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: update_uniapp

on:
  schedule:
    - cron: 0 21 * * *
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: yarn global add npm-check-updates@11 inquirer
    - run: yarn update -y
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 更新uniapp及其他依赖
